import { PERMISSIONS, type Role } from '@mystore/contracts';

/**
 * Role → permission expansion (spec §12, §68).
 *
 * Admin-tier roles receive every known permission; operational roles
 * receive an explicit subset matching their business function.
 */
const ALL_PERMISSIONS: string[] = Object.values(PERMISSIONS);

const ADMIN_ROLES: Role[] = ['SUPER_ADMIN', 'PLATFORM_ADMIN', 'ORG_ADMIN', 'COMPANY_ADMIN'];

const ROLE_PERMISSIONS: Partial<Record<Role, string[]>> = {
  BRANCH_MANAGER: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_WRITE, PERMISSIONS.SALES_VOID, PERMISSIONS.SALES_REFUND,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.LOCATIONS_READ, PERMISSIONS.LOCATIONS_WRITE,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_WRITE, PERMISSIONS.PROCUREMENT_RECEIVE,
    PERMISSIONS.PROMOTIONS_READ, PERMISSIONS.PROMOTIONS_WRITE,
    PERMISSIONS.PRICING_READ, PERMISSIONS.PRICING_WRITE,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.WMS_READ, PERMISSIONS.WMS_WRITE,
    PERMISSIONS.TRANSFERS_READ, PERMISSIONS.TRANSFERS_WRITE, PERMISSIONS.TRANSFERS_APPROVE, PERMISSIONS.TRANSFERS_RECEIVE,
    PERMISSIONS.TAXES_READ, PERMISSIONS.TAXES_WRITE,
    PERMISSIONS.LOYALTY_READ, PERMISSIONS.LOYALTY_WRITE,
    PERMISSIONS.STORAGE_READ, PERMISSIONS.STORAGE_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
  ],
  SALES_MANAGER: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_WRITE, PERMISSIONS.SALES_VOID, PERMISSIONS.SALES_REFUND,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.PROMOTIONS_READ, PERMISSIONS.PROMOTIONS_WRITE,
    PERMISSIONS.PRICING_READ, PERMISSIONS.PRICING_WRITE,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.TRANSFERS_READ, PERMISSIONS.TRANSFERS_WRITE,
    PERMISSIONS.TAXES_READ,
    PERMISSIONS.LOYALTY_READ, PERMISSIONS.LOYALTY_WRITE,
    PERMISSIONS.STORAGE_READ, PERMISSIONS.STORAGE_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
  ],
  FINANCE_MANAGER: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_REFUND,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.PROMOTIONS_READ,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TAXES_READ, PERMISSIONS.TAXES_WRITE,
    PERMISSIONS.LOYALTY_READ, PERMISSIONS.LOYALTY_WRITE,
    PERMISSIONS.STORAGE_READ, PERMISSIONS.STORAGE_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_WRITE, PERMISSIONS.JOURNAL_POST,
    PERMISSIONS.WORKFLOW_READ, PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.TICKETS_READ, PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.DEVELOPER_READ, PERMISSIONS.DEVELOPER_WRITE, PERMISSIONS.WEBHOOKS_MANAGE,
    PERMISSIONS.TELEGRAM_MANAGE,
    PERMISSIONS.AUTOMATION_READ, PERMISSIONS.AUTOMATION_WRITE, PERMISSIONS.AUTOMATION_EXECUTE,
  ],
  WAREHOUSE_MANAGER: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_RECEIVE,
    PERMISSIONS.WMS_READ, PERMISSIONS.WMS_WRITE,
    PERMISSIONS.TRANSFERS_READ, PERMISSIONS.TRANSFERS_WRITE,
    PERMISSIONS.TRANSFERS_APPROVE, PERMISSIONS.TRANSFERS_RECEIVE,
    PERMISSIONS.STORAGE_READ, PERMISSIONS.STORAGE_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTS_READ,
  ],
  CASHIER: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.SALES_READ, PERMISSIONS.SALES_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.PROMOTIONS_READ,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.LOYALTY_READ,
    PERMISSIONS.STORAGE_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  STAFF: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.STORAGE_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.INVENTORY_READ,
  ],
  ACCOUNTANT: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.FINANCE_READ, PERMISSIONS.FINANCE_WRITE, PERMISSIONS.JOURNAL_POST,
  ],
  AUDITOR: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.FINANCE_READ,
  ],
};

/** Computes the flat, de-duplicated permission set for a user's roles. */
export function expandPermissions(roles: Role[]): string[] {
  const set = new Set<string>();
  for (const role of roles) {
    if (ADMIN_ROLES.includes(role)) {
      ALL_PERMISSIONS.forEach((p) => set.add(p));
    } else {
      (ROLE_PERMISSIONS[role] ?? []).forEach((p) => set.add(p));
    }
  }
  return [...set];
}
